version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=2222
      - DATABASE_NAME=pelith
    depends_on:
      - db
    volumes:
      - ./config:/app/config

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=2222
      - POSTGRES_DB=pelith
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
